version: '3'
services:
  web:
    image: buzzword-stack/frontend
    build: Frontend/.
    container_name: buzzwordstack_frontend
    restart: always
    expose:
      - 8080
    # ports:
    #   - "8080:8080"
  api:
    image: buzzword-stack/backend
    build: Backend/.
    container_name: buzzwordstack_backend
    restart: always
    links:
      - db
    expose: 
      - 5000
    # ports:
    #   - "5000:5000"
  proxy:
    image: buzzword-stack/proxy
    build: Proxy/.
    container_name: buzzwordstack_proxy
    restart: always
    links:
      - web
      - api
    ports:
      - 80:80
  db:
    container_name: buzzwordstack_db
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: safeuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose: 
      - 5432
  adminer:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - 8000:8080
volumes:
  db-data: