version: '3'
services:
  web:
    image: dmium/buzzword-stack_frontend
    container_name: buzzwordstack_frontend
    restart: always
    expose:
      - 8080
  api:
    image: dmium/buzzword-stack_backend
    container_name: buzzwordstack_backend
    restart: always
    links:
      - db
    environment: 
      DB_URI: "postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}/${DB_NAME}"
    expose: 
      - 5000
  proxy:
    image: dmium/buzzword-stack_proxy
    container_name: buzzwordstack_proxy
    restart: always
    links:
      - web
      - api
    ports:
      - 80:80
  db:
    container_name: buzzwordstack_db
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: safeuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose: 
      - 5432
#   adminer:
#     image: adminer
#     restart: always
#     links:
#       - db
#     ports:
#       - 8000:8080
volumes:
  db-data: