apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: registry.digitalocean.com/buzzword-stack-container-registry-dom/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: backend
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: database-connection
                key: dbname
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: database-connection
                key: dbpass
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: database-connection
                key: dbport
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: database-connection
                key: dbuser
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: database-connection
                key: dbhost
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: backend
