name: Unit Tests

on:
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - run: npm install
        working-directory: "Application/Frontend/buzzword-stack-frontend"
      - run: npm run test:unit
        working-directory: "Application/Frontend/buzzword-stack-frontend"
      - name: Setup backend
        run: ./setup-docker.sh
        working-directory: "Application/Backend/api/src"
      - name: Run backend unit tests
        run: ~/.local/bin/pytest
        working-directory: "Application/Backend/api"
